/**
 * Complete PayPal Flow Test
 * This script simulates a complete payment flow from creation to capture
 */

require('dotenv').config();
const paypal = require('./services/paypal');

console.log('\n' + '='.repeat(70));
console.log('  COMPLETE PAYPAL PAYMENT FLOW TEST');
console.log('='.repeat(70) + '\n');

async function testCompleteFlow() {
    try {
        // Step 1: Create Order
        console.log('📝 Step 1: Creating PayPal Order...');
        const testAmount = '25.99'; // SGD 25.99
        const order = await paypal.createOrder(testAmount);
        
        if (!order || !order.id) {
            console.log('   ✗ Failed to create order');
            console.log('   Response:', JSON.stringify(order, null, 2));
            return;
        }
        
        console.log('   ✓ Order created successfully!');
        console.log('   Order ID:', order.id);
        console.log('   Status:', order.status);
        console.log('   Amount:', testAmount, 'SGD');
        
        // Extract approval URL
        const approvalLink = order.links?.find(link => link.rel === 'approve');
        if (approvalLink) {
            console.log('\n   🔗 Customer Approval URL:');
            console.log('   ', approvalLink.href);
            console.log('\n   In a real scenario, the customer would:');
            console.log('   1. Click the PayPal button');
            console.log('   2. Be redirected to this URL');
            console.log('   3. Login to PayPal sandbox');
            console.log('   4. Approve the payment');
            console.log('   5. Be redirected back to your application');
        }
        
        // Step 2: Explain the capture process
        console.log('\n💳 Step 2: Payment Capture Process');
        console.log('   ⚠  NOTE: In sandbox mode, you CANNOT capture a payment');
        console.log('   without the customer approving it first.\n');
        console.log('   The capture happens AFTER the customer:');
        console.log('   • Clicks "Pay Now" on PayPal');
        console.log('   • Confirms the payment');
        console.log('   • Returns to your application\n');
        console.log('   Your application then calls /api/paypal/capture-order');
        console.log('   to finalize the payment and transfer the funds.');
        
        // Step 3: Test the complete flow in browser
        console.log('\n🌐 Step 3: Complete the Test in Your Browser');
        console.log('   To test the full payment flow:');
        console.log('   1. Open: http://localhost:3000');
        console.log('   2. Login or register');
        console.log('   3. Add items to cart');
        console.log('   4. Go to checkout');
        console.log('   5. Select PayPal as payment method');
        console.log('   6. Click the PayPal button');
        console.log('   7. Login with PayPal sandbox test account');
        console.log('   8. Approve the payment');
        console.log('   9. Verify success page\n');
        
        // Summary
        console.log('\n' + '='.repeat(70));
        console.log('  TEST SUMMARY');
        console.log('='.repeat(70));
        console.log('\n  ✓ PayPal API Connection: WORKING');
        console.log('  ✓ Create Order Endpoint: WORKING');
        console.log('  ✓ Order ID Generated:', order.id);
        console.log('  ✓ Amount Configured:', testAmount, 'SGD');
        console.log('  ✓ Approval Flow: READY');
        console.log('\n  Next Step: Test the complete flow in your browser');
        console.log('  URL: http://localhost:3000/checkout\n');
        
        // Additional Info
        console.log('='.repeat(70));
        console.log('  PAYPAL SANDBOX TEST ACCOUNT INFO');
        console.log('='.repeat(70));
        console.log('\n  To complete a payment, you need a Personal (buyer) test account.');
        console.log('  Create one at: https://developer.paypal.com/dashboard/accounts\n');
        console.log('  Your test account will have:');
        console.log('  • Email: something like sb-xxxxx@personal.example.com');
        console.log('  • Password: (generated by PayPal)');
        console.log('  • Balance: Virtual money to make test purchases\n');
        
        console.log('='.repeat(70));
        console.log('  INTEGRATION STATUS: ✓ READY FOR TESTING');
        console.log('='.repeat(70) + '\n');
        
    } catch (error) {
        console.log('\n✗ Error occurred:');
        console.log('   Message:', error.message);
        console.log('   Stack:', error.stack);
        console.log('\n   Please check:');
        console.log('   • Your .env file has correct credentials');
        console.log('   • Your internet connection is working');
        console.log('   • PayPal API is accessible\n');
    }
}

// Run the test
testCompleteFlow();
